import { TUseFooterItemEditorProps } from "../../app/View/tablet/Drawer/FooterItemEditor/view/FooterItemEditor";

export const propsFooterItemEditor: TUseFooterItemEditorProps = {
         onTapRadio: "modal",
         setOnTapRadio: null,
         isEditting: false,
         titleText: "",
         editorText: "",
         setEditorText: null,
         setEditorTextExcerpt: null,
         selectedIcon: null,
         dispatchSelectedIcon: null,
         linkUrl: null,
         setLinkUrl: null,
         appLinkUrl: null,
         setAppLinkUrl: null,
         charCountFooterItemContent: 0,
         setCharCountFooterItemContent: null,
         handleOnChangeIconName: null,
         handleSubmit: null,
         modalSizeRadio: "large",
         setModalSizeRadio: null,
         dataType: "default_data",
         setDataType: null,
         is_admin: false,
         isMobile: false,
         onSidebar: false,
         handleOnSidebar: null,
         edittingFooterItemParams: null,
       };
