import { FooterItems } from '../interface/Interface';

export const samplefooterItems: FooterItems = [
  {
    footer_item_id: 2,
    is_published: true,
    created_at: '2020-05-24T07:18:51.000Z',
    updated_at: '2020-05-24T07:19:01.000Z',
    icon_name: '雑誌',
    displayed_icon_name: 'MenuBookTwoTone',
    on_tap: 'modal',
    item_content: '<h1>雑誌！？</h1>',
    item_excerpt: '雑誌！？...',
    link_url: '',
    order: 1,
    order_sidebar: 0,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    data_type: 'default_data',
  },
  {
    footer_item_id: 3,
    is_published: false,
    created_at: '2020-05-24T07:19:28.000Z',
    updated_at: '2020-05-24T13:31:52.000Z',
    icon_name: '',
    displayed_icon_name: '',
    on_tap: 'modal',
    item_content: '',
    item_excerpt: '',
    link_url: 'https://naokihair.com/ja/top-2/',
    order: 2,
    order_sidebar: 0,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    data_type: 'sample_data',
  },
  {
    footer_item_id: 4,
    is_published: true,
    created_at: '2020-05-26T08:03:37.000Z',
    updated_at: null,
    icon_name: '雑誌',
    displayed_icon_name: 'MenuBookTwoTone',
    on_tap: 'appLink',
    item_content: '',
    item_excerpt: '',
    link_url: '',
    order: 3,
    order_sidebar: 0,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    data_type: 'default_data',
  },
  {
    footer_item_id: 4,
    is_published: true,
    created_at: '2020-05-26T08:03:37.000Z',
    updated_at: null,
    icon_name: '名前がながいよどんな表示になる？',
    displayed_icon_name: 'MenuBookTwoTone',
    on_tap: 'modal',
    item_content: '',
    item_excerpt: '',
    link_url: '',
    order: 4,
    order_sidebar: 0,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    data_type: 'default_data',
  },
  {
    footer_item_id: 4,
    is_published: false,
    created_at: '2020-05-26T08:03:37.000Z',
    updated_at: null,
    icon_name: '雑誌下書き',
    displayed_icon_name: 'MenuBookTwoTone',
    on_tap: 'appLink',
    item_content: '',
    item_excerpt: '',
    link_url: '',
    order: 5,
    order_sidebar: 0,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    data_type: 'default_data',
  },
];
