import { FooterItems } from "../app/Store/Types";

export const samplefooterItems: FooterItems = [
  {
    footer_item_id: 2,
    is_published: true,
    created_at: "2020-05-24T07:18:51.000Z",
    updated_at: "2020-05-24T07:19:01.000Z",
    icon_name: "雑誌",
    displayed_icon_name: "MenuBookTwoTone",
    on_tap: "modal",
    item_content: "<h1>雑誌！？</h1>",
    item_excerpt: '雑誌！？...',
    link_url: "",
    order: 1,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    is_sample_data: false,
  },
  {
    footer_item_id: 3,
    is_published: true,
    created_at: "2020-05-24T07:19:28.000Z",
    updated_at: "2020-05-24T13:31:52.000Z",
    icon_name: "",
    displayed_icon_name: null,
    on_tap: "link",
    item_content: "",
    item_excerpt: '',
    link_url: "https://naokihair.com/ja/top-2/",
    order: 2,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    is_sample_data: false,
  },
  {
    footer_item_id: 4,
    is_published: true,
    created_at: "2020-05-26T08:03:37.000Z",
    updated_at: null,
    icon_name: "雑誌",
    displayed_icon_name: "MenuBookTwoTone",
    on_tap: "modal",
    item_content: "",
    item_excerpt: '',
    link_url: "",
    order: 3,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    is_sample_data: false,
  },
  {
    footer_item_id: 4,
    is_published: true,
    created_at: "2020-05-26T08:03:37.000Z",
    updated_at: null,
    icon_name: "名前がながいよどんな表示になる？",
    displayed_icon_name: "MenuBookTwoTone",
    on_tap: "modal",
    item_content: "",
    item_excerpt: '',
    link_url: "",
    order: 4,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    is_sample_data: false,
  },
  {
    footer_item_id: 4,
    is_published: true,
    created_at: "2020-05-26T08:03:37.000Z",
    updated_at: null,
    icon_name: "雑誌",
    displayed_icon_name: "MenuBookTwoTone",
    on_tap: "modal",
    item_content: "",
    item_excerpt: '',
    link_url: "",
    order: 5,
    user_id: 1,
    app_link_url: '',
    modal_size: 'large',
    is_sample_data: false,
  },
];
